### ISSUE TITLE
No problems, just thanks

### ISSUE THREAD

**Issue by spiralsteno** [xenova/chat-replay-downloader#13]
I'm bad at github and couldn't see any other way to send this.

Just wanted to say how much I appreciate this. I found this script via google leading me to a random stackexchange answer, and it was just what I needed when I needed it most. Helped me save some things in the eleventh hour that had a lot of sentimental value and would have otherwise been totally lost.

Thanks so much for making this, honestly.

**Comment by xenova** [comment]
Haha thanks so much! 😄 Glad it was useful! 😊
