### ISSUE TITLE
Receving duplicated superchats

### ISSUE THREAD

**Issue by lekoOwO** [xenova/chat-replay-downloader#14]
As title, superchats received are duplicated (Some superchats are received twice).

May try [this](https://www.youtube.com/watch?v=97w16cYskVI) and search for a few superchat authors or text contents.

**Comment by xenova** [comment]
Hey there 👋 Thanks for the report. I actually remember having a similar issue before, when some messages were being duplicated because the YouTube API actually duplicates messages for ticker messages and stickers (it sends two actions each time). I initially overcame this by ignoring one of them, but there might be something I did not account for.

Can you maybe give an example of some messages you are seeing double or? (Perhaps the log you get when running the program or something?) I see you provided a url above, so if you can give me a timestamp or something, that would be great! Thanks.

**Comment by lekoOwO** [comment]
Oh, there's a ticker message.

**Comment by lekoOwO** [comment]
After I ignored the ticker message, it seems normal now...?
But there's a thing i'm confused.

My code shows that [This video](https://playboard.co/en/video/97w16cYskVI):
```
UUID: 77820f66-01c3-4b39-a97e-6a0fddb224ee

Total: 478211.4029 TWD
2856 super chats received.
29 super stickers received.
0 new subscribers received.
```

But the site shows that it has `NT$625,905.20` (NT$ == TWD)

Is the data somewhat wrong?

**Comment by xenova** [comment]
That is interesting. I am not too sure how they get their data, but this tool "scrapes" it directly from the video page, and I am quite sure that no messages are missing.

However, if you can find an example of a superchat message which is visible on YouTube, but not with the tool, then I will definitely do my best to fix it!

**Comment by lekoOwO** [comment]
Hmm it's really quite interesting.

I'll try giving them a email see wuts happening.

**Comment by xenova** [comment]
> Hmm it's really quite interesting.
> 
> I'll try giving them a email see wuts happening.

Okay great! :)

**Comment by lekoOwO** [comment]
Hm
they says that the replay comment will never be complete
thus they records it while it's on live.
seems that we cant do anything to fix it :(

**Comment by xenova** [comment]
Okay that's unfortunate, but it does not necessarily mean that this tool does not work as intended. Perhaps they might be double counting? In any case, you could check it manually and see which tool does not work properly. If it is this code, you can let me know the video and timestamp of when the error occurred and I will fix it as soon as possible! 👍

**Comment by lekoOwO** [comment]
Quote, a part of their reply:

> 1. For some reasons, the replay excludes some superchats; these symptoms were found on a number of broadcasts.
> 2. The statistics we provide include all superchats that occurred before the broadcast began.
>
> (97w16cYskVI) In this video , the actual first superchat occurred at 2:00 am (GMT+8), but the replay only shows the superchat that occurred after 5:22 am (GMT+8).

> There is no possibility that the superchat statistics we provide will be redundantly calculated.

Seems that they're quite confident that they didn't double count www

**Comment by xenova** [comment]
Oh okay, so the issue is then with how YouTube shows the superchat in the chat replay. That's quite unfortunate. Perhaps https://developers.google.com/youtube/v3/live/docs/superChatEvents would be useful?

**Comment by lekoOwO** [comment]
Hmmm... The API is interesting

Will dig in for it see if it helps
