### ISSUE TITLE
support youtube top char

### ISSUE THREAD

**Issue by shuiqukeyou** [xenova/chat-replay-downloader#16]
Youtube live normal normal message is two types of messages

Top chat: This view filters messages such as potential spam to help make chat easier to read and more useful.
Live chat: This view is not filtered. It shows all chat messages as they come in.

I noticed that the message obtained by this project is all the messages, that is, Live chat, which contains a lot of spam.
Is there any way to get only Top chat, or separate Top chat

**Comment by xenova** [comment]
Sure, I can add this as an option :) I will update you when I'm done 👍

**Comment by xenova** [comment]
@shuiqukeyou Let me know if that works as expected 👍

**Comment by shuiqukeyou** [comment]
It works fine, thanks for your help
