### ISSUE TITLE
ModuleNotFoundError: No module named 'emoji'

### ISSUE THREAD

**Issue by ReddPizzai** [xenova/chat-replay-downloader#23]
Sorry if this is dumb, but I unzipped and did the pip requirements install, but every time I run the script I get 
```
Traceback (most recent call last):
  File "run_tests.py", line 1, in <module>
    from chat_replay_downloader import *
  File "~/chat-replay-downloader-master/chat_replay_downloader.py", line 9, in <module>
    import emoji
ModuleNotFoundError: No module named 'emoji'
```
No experience with python so I have no clue what it means or how to fix it

**Comment by ccdffddfddfdsfedeee** [comment]
Use `pip3` instead of `pip`

**Comment by ReddPizzai** [comment]
> Use `pip3` instead of `pip`

thanks :/

**Comment by xenova** [comment]
Hi there. Yes, as @ccdffddfddfdsfedeee mentioned, you should install the requirements in a python 3 environment. Python 2 has been deprecated since January 1, 2020.

Let me know if you still have any issues though! 😄
