### ISSUE TITLE
Bad python packaging and dependency management

### ISSUE THREAD

**Issue by hazarek** [xenova/chat-replay-downloader#24]
it needs `chmod 755 ./chat_replay_downloader.py` on macos or gives `zsh: permission denied:` Installation is easier if you package it as a console script.
1. Add setup.py
2. make[ console script](https://setuptools.readthedocs.io/en/latest/userguide/entry_point.html?highlight=console%20script#console-scripts)
3. Write the version numbers into setup.py and requirements.txt

Also, long argument names start with double hyphens. Other argument names are not similar with `-h --help`.

**Comment by xenova** [comment]
Good idea! :) I can definitely do this. I'm currently busy with some other projects (with more strict deadlines), so I'll only be able to finish this in around a week.

**Comment by xenova** [comment]
@hazarek Just an update on this. I'm still busy in another branch with improving packaging
(https://github.com/xenova/chat-replay-downloader/tree/package)

Slowly getting there 👍
