### ISSUE TITLE
Youtube chat issues

### ISSUE THREAD

**Issue by artiction** [xenova/chat-replay-downloader#25]
Sorry, I have no idea how to code, but it seems that there's an error for retrieving Youtube live chats. Here's the traceback:

```
  File "C:\Windows\System32\chat-replay-downloader-master\test.py", line 477, in <module>
    chat_messages = chat_downloader.get_chat_replay(
  File "C:\Windows\System32\chat-replay-downloader-master\test.py", line 429, in get_chat_replay
    return self.get_youtube_messages(match.group(1), start_time, end_time, message_type, chat_type)
  File "C:\Windows\System32\chat-replay-downloader-master\test.py", line 271, in get_youtube_messages
    continuation_by_title_map = self.__get_initial_youtube_info(video_id)
  File "C:\Windows\System32\chat-replay-downloader-master\test.py", line 168, in __get_initial_youtube_info
    ytInitialData_script = next(script.string for script in soup.find_all(
StopIteration
```

**Comment by xenova** [comment]
Can you provide the command you ran?

**Comment by artiction** [comment]
i renamed the file and even running
`python test.py <url> still leads to the same problem`
i usually use it like this
`python test.py -message_type all https://www.youtube.com/watch?v=C_aOhzaXsAA -output 22okayu.txt`

**Comment by xenova** [comment]
That's strange. I've run the command you gave me an it's working correctly. Are you sure you are using the correct version of Python (Python 3 required)? Also, does this happen every time you run it?

**Comment by xenova** [comment]
Also make sure you have the necessary python modules installed. `pip install -r requirements.txt`

**Comment by artiction** [comment]
i did run pip install again, but ill check about python3, thanks!

**Comment by xenova** [comment]
You can also run `python --version` to check what version is installed.

It might be the case (usually for mac users), that you need to run the program with `python3` instead.
e.g. `python3 test.py -message_type all https://www.youtube.com/watch?v=C_aOhzaXsAA -output 22okayu.txt`

**Comment by artiction** [comment]
Same result now after reinstalling.
Before I reinstalled it, I was able to run python3 with the same result as python (all those traceback lines)
Also I'm using Windows.

**Comment by xenova** [comment]
I'm not too sure what the issue is then. The same command you gave works perfectly fine on my computer. Also, is there a reason you are running this from `C:\Windows\System32\chat-replay-downloader-master\test.py` ? ... Try move it to a different location (e.g. Desktop) perhaps? There may be some permission issues?

**Comment by artiction** [comment]
I have tried that too, actually.. I have no idea at this point.

**Comment by xenova** [comment]
Oh that's very strange. Never had that issue before 👀 ... I'll add a message for the user in case this happens again to someone else. Thanks for making the report! 👍
