### ISSUE TITLE
Unable to parse video data

### ISSUE THREAD

**Issue by artiction** [xenova/chat-replay-downloader#28]
I've tried the usual script on like 3 different streams now.
The response is always "Unable to parse video data."
I know it's not my connection since I've tried it with and without VPN numerous times. Any idea why this happens?

**Comment by xenova** [comment]
Can you provide the command you ran?

**Comment by xenova** [comment]
Let me know if https://github.com/xenova/chat-replay-downloader/commit/efb8131a747b37ecc0a92b2c87e7d6137edf0489 fixes your issue.

**Comment by artiction** [comment]
Alright, it works great, although before this version,
let's just say there are currently 10 messages in the live chat, the older version could grab them all, so I liked that a bit.
Thanks for the fix though, appreciate it!

**Comment by xenova** [comment]
Can you provide an example? I actually did not change anything that would cause that, which is quite strange.
