### ISSUE TITLE
Comments from first minutes aren't downloaded

### ISSUE THREAD

**Issue by ZobaJakColbert** [xenova/chat-replay-downloader#29]
Today I tried download two different live chats, and on each one first couple of minutes of comments aren't downloaded. First comment downloading is like 3 or 5 minutes after truely first comment.

**Comment by xenova** [comment]
Hi there. Can you please provide the code you ran? There is no way for me to debug without that information. Thanks!

**Comment by xenova** [comment]
Okay, it turns out YouTube added a `clickTrackingParams` field which blocked correct information from being read. The latest commit should fix this. Let me know if it works 👍

**Comment by ZobaJakColbert** [comment]
Yeah, now it's working correctly.
