### ISSUE TITLE
Superchats

### ISSUE THREAD

**Issue by artiction** [xenova/chat-replay-downloader#30]
I'm so sorry but the new version isn't saving superchats..

**Comment by xenova** [comment]
Hi, which version are you talking about? The `package` branch is not ready for release yet (hence why it has not been merged back into `master`.

Also, are you running with the correct flags? Please provide the code you ran.

**Comment by artiction** [comment]
Okay, nevermind. Your recently updated code works perfectly. Thanks for keeping the code updated! Everything works fine now.

**Comment by xenova** [comment]
Okay great! 👍 No worries! 😄
