### ISSUE TITLE
about SQLite3 support to which branch

### ISSUE THREAD

**Issue by ladalevis** [xenova/chat-replay-downloader#31]
I really appreciate your work, and I find a small problem that sometimes the script break down (due to google) and all the data got lost before write to a file. So **I'm going to** add support for SQLite to write data into a file, like chat_data.db so that nothing will get lost. I just wondering which branch should I address on, the master branch that have  one py file or the 
new package branch, or both?

**Comment by xenova** [comment]
Hi there! Wow this is awesome! 👍 

I will eventually be switching to the `package` branch, so you could integrate it into there. However, it is still in development, so you might still find strange comments and test-code lying around... 😅 

Any work - like this - is greatly appreciated! Thanks!
