### ISSUE TITLE
Error caused by empty author name during youtube live stream

### ISSUE THREAD

**Issue by pupkinvaska** [xenova/chat-replay-downloader#32]
After an error, the script stops and the result is not saved to file.
Used .csv output.
Error caused by **empty** author name.
It would be better if the file was written by adding new lines continuously then the result would not be lost.

Traceback (most recent call last):
```
  File "*\chat_replay_downloader.py", line 638, in <module>
    chat_messages = chat_downloader.get_chat_replay(
  File "*\chat_replay_downloader.py", line 562, in get_chat_replay
    return self.get_youtube_messages(match.group(1), start_time, end_time, message_type, chat_type, callback)
  File "*\chat_replay_downloader.py", line 473, in get_youtube_messages
    callback(data)
  File "*\chat_replay_downloader.py", line 615, in print_item
    chat_downloader.print_item(item)
  File "*\chat_replay_downloader.py", line 208, in print_item
    message = emoji.demojize(self.message_to_string(item))
  File "*\chat_replay_downloader.py", line 199, in message_to_string
    item['author'],
KeyError: 'author'
```

**Comment by xenova** [comment]
Oh, that is strange... Can you give an example of the command you ran? 

On that note, how would you recommend "continuously" writing lines to the csv? Because, the columns are not known in advance. This means that the file will have to be rewritten each time a new column is identified. This might be fine for smaller files, but it may have issues with larger files (not too sure yet though).

Another option is to write all possible columns to the CSV and then have a lot of empty columns.

**Comment by pupkinvaska** [comment]
my command: 
python chat_replay_downloader.py https://www.youtube.com/watch?v=*** -start_time 0 -output C:\***\stream.csv
Windows 10, python 3.9. 
It's easy to add new lines to csv because it's simple text file of values delimited by commas. Column structure usually does not change. I'll try txt.

**Comment by xenova** [comment]
Okay that sounds good 👍

Can you perhaps give me the url/ID of the video you were testing? If you're not comfortable with that, you can always email it to me :)

**Comment by pupkinvaska** [comment]
Very rarely a user does not have a name. You can’t wait for him to appear in the chat. Better to reproduce the case by yourself.
Maybe you can try just using a space as author name, if comment['commenter']['display_name'] is empty to make the script run without errors.

**Comment by xenova** [comment]
Okay this should fix it 👍
