### ISSUE TITLE
Live Chat Replay

### ISSUE THREAD

**Issue by AaronTrotter** [xenova/chat-replay-downloader#35]
How can I be sure youtube live chat replay is returning the all the comments and not just the top chat?

It definitely is excluding a lot of them.

**Comment by xenova** [comment]
Can you please give an example? (The command you used including the YouTube video URL)

The tool should display everything which appears on the chat replay, so if you can find a message which is displayed on the website, but not retrieved, I'll be sure to look into it further.

**Comment by AaronTrotter** [comment]
Hey! Thanks for coming back to me so quickly.

We would like to use this tool to retrieve the chat from [](https://www.youtube.com/watch?v=fqnnU6s_SBw&t=789s)
There should be over 1.5million messages but your tool is returning 11k.

I used the cmd `py chat_replay_downloader.py https://www.youtube.com/watch?v=fqnnU6s_SB -output example.csv`

**Comment by xenova** [comment]
Are you sure there are 1.5 million messages?

The video is 23 minutes long, with only 400k views. If there are 1.5 million messages, that would mean ~11k **per second**, which I highly doubt is correct.

If you check out the chat replay, the number of messages seems to correspond with what the tool is getting (~8 per second)

**Comment by AaronTrotter** [comment]
This is what YT analytics is telling me.

The youtube cap is 2000 live chat messages per second and the aim of this video was an interactive experience which required people to constantly type into the chat

Per-minute that would be 120k if we reached the maximum limit which we did on a few occasions. Youtube would frequently say "Network busy" and prevent users from typing. The game interacted with youtube via the YT Live API which was also limited to 2000 per second and i can confirm we had hit this in-game. The reason we want to use your tool is because the live video no longer has a live chat id and so we are look at other means of extracting the names of players.

Perhaps this is something you would be interested in helping us on and we can take this off git and into email? Perhaps we could hire you for a few hours to take a look to see if this is possible?

**Comment by xenova** [comment]
Oh that is quite strange indeed. The tool works by loading the video page and simulating http requests for the next "continuation" of the live chat replay. So, the tool will retrieve everything to be shown by the chat replay. In other words, the tool will only ever show what is visible on the YouTube video page.

I suppose YouTube implemented a cap when showing messages from a past live stream (possibly for a case such like this) to improve the viewer's experience (i.e. not loading 1.5 million messages). The tool does allow for passing a cookies file to the program, but I'm unsure whether this will fix anything.

A simple google search for missing YouTube livestream messages does not seem to yield any results, so it must be a "feature" they added in without documenting.

Excuse me for not knowing, but on the "uploader's side", can you see all the messages? Do they provide an option for downloading everything? Is there a similar UI for seeing all the messages? I understand that YouTube says that 1.5 million messages were sent, but do they provide a means of accessing it?

If you want, you can send me an email at admin@xenova.com for us to discuss further - this is quite intriguing!

**Comment by artiction** [comment]
Sorry to butt in, but pretty sure Youtube limits it on the live chat replay.
