### ISSUE TITLE
Super chat messages are skipped during live stream

### ISSUE THREAD

**Issue by pupkinvaska** [xenova/chat-replay-downloader#36]
My command:
`python chat_replay_downloader.py https://www.youtube.com/watch?v=* -message_type all -output *.csv`

Used parameter `-message_type all`, but paid super chat messages are skipped during live stream. They are missing in the file and in the console output. Several of regular messages following the super chat are missing too.
Super chat from completed streams are saved correctly. But no need to write colors and duration of pinned messages, as useful information is only sum of donation. it would be great if it was possible to customize output.

**Comment by xenova** [comment]
Could you please provide the ID of the YouTube video for which this happened? Also, which messages were missed? Can you provide a time stamp for a message which should have been shown, but was not? The tool should retrieve all messages which are visible on YouTube.

Additionally, I have been working on a custom formatting system which will be included in an upcoming update.

**Comment by xenova** [comment]
Also, please ensure you are using the latest version of the software. YouTube made some changes recently, which caused some similar issues to this - which should have been fixed in the latest release.

**Comment by ladalevis** [comment]
It happens sometimes and suddenly get disappeared. Currently there is no problem. It is wired, and I think YouTube has changed its API just few days ago.

**Comment by pupkinvaska** [comment]
@xenova sorry can not provide ID, as the video was removed.  You can check any other ongoing streams on Youtube.  Noticed this behavior more than once on different channels.

Version downloaded 9th, Dec. Will try update.

**Comment by xenova** [comment]
Okay yes, the latest release (v1.0.1) should fix it then 👍

**Comment by pupkinvaska** [comment]
thanks, I will give feedback if I find any bugs
