### ISSUE TITLE
Retracted messages

### ISSUE THREAD

**Issue by aminoacie** [xenova/chat-replay-downloader#38]
Sorry, this isn't much of an issue, but do you think it's possible to get retracted / unsent messages with the script?

**Comment by xenova** [comment]
Hi there 😄 ... Yes, I have been working on this for the next version of the software (currently in development in the `package` [branch](https://github.com/xenova/chat-replay-downloader/tree/package)). Are you talking about YouTube or Twitch in particular - or for both?

**Comment by aminoacie** [comment]
Youtube, although it's a message from like 15 hours ago + the stream already started and it seems that the script can't grab it. So i assume it's impossible?

**Comment by xenova** [comment]
Oh I see... the tool would only be able to get messages that are deleted during a stream.

When rewatching a stream (i.e. getting the chat replay), YouTube does not display messages that were deleted while the stream was active. So, for that specific use case, I don't think it is possible.

**Comment by aminoacie** [comment]
Yeah, I also feel like that's the case. Thanks.
