### ISSUE TITLE
Negative YouTube Start Times Don't Work

### ISSUE THREAD

**Issue by Yay295** [xenova/chat-replay-downloader#4]
It's possible to comment on YouTube streams before they go live, and the comments get a negative timestamp. If you use a negative value with this though it crashes either after the first batch of comments, or after it reaches positive comments. I'm not sure which; I don't have a video with enough pre-comments for it to have more than one batch.

**Comment by Yay295** [comment]
It looks like removing `playerOffsetMs` from the `__YOUTUBE_API_TEMPLATE` will get all of the comments even from before the start. That should probably be the default.

**Comment by xenova** [comment]
Oh yes I remember something like that - I can try add it so that it does work with negative numbers, instead of not allowing it (in your pull request). Give me a moment and I'll see if I can get it working! :)
