### ISSUE TITLE
Parse youtube link return redirect url

### ISSUE THREAD

**Issue by ebir25** [xenova/chat-replay-downloader#43]
parse_message_runs call parse_youtube_link with url ( url: 'https://www.youtube.com/...' ). fail when check startswith '/redirect' and '/watch' => return url 
![IMG_20210107_204829](https://user-images.githubusercontent.com/75713351/103901775-2b316380-512c-11eb-80da-275b3cb1dddc.jpg)

**Comment by ebir25** [comment]
I check again with data from live chat. url in live chat different from url in replay chat.
![IMG_20210107_214219](https://user-images.githubusercontent.com/75713351/103905477-3dfa6700-5131-11eb-8e69-9200101e7caf.jpg)

**Comment by xenova** [comment]
Oh right, I've made this fix in the `package` branch already... let me add the code to the master branch too.

Could you send me the URL you used, so that I can test it again?

**Comment by xenova** [comment]
@ebir25 Let me know if https://github.com/xenova/chat-replay-downloader/commit/1546d1732054040af365fa5941093c821b429b2e fixes it
