### ISSUE TITLE
Unable to parse video data

### ISSUE THREAD

**Issue by artiction** [xenova/chat-replay-downloader#44]
Suddenly not working, for the last 2 hours ago, the script was still working perfectly.
Script was something like this:
`python tester.py -message_type all https://www.youtube.com/watch?v=EVLjth4lJXY -output EVLjth4lJXY1.txt`

Awaiting your reply.

**Comment by xenova** [comment]
Hi. The script is working for me? This might mean you are getting 429 errors (i.e. Too many requests) from YouTube.

In order to debug, you could add to line 258 of `chat_replay_downloader.py`
```python
print(html.text)
```

The next version of the software has much better error reporting, so you would have to do this in the meantime.

**Comment by djamg** [comment]
Same issue! "Unable to parse video data" error

**Comment by xenova** [comment]
> Same issue! "Unable to parse video data" error

Okay, can you please do what I said above to help me debug it? I can't fix the problem if I don't know what exactly is happening.

Thanks 👍

**Comment by artiction** [comment]
Doesn't look like it work after adding print(html.text).. I should write it in like this, right?
```
        html = self.__session_get(original_url)
        print(html.text)
        info = re.search(self._YT_INITIAL_DATA_RE, html.text)
```
That's line 257, 258, and 259.

**Comment by xenova** [comment]
Yes that is correct.
[chat_replay_downloader_test.zip](https://github.com/xenova/chat-replay-downloader/files/5794236/chat_replay_downloader_test.zip)

Can you try run this with those arguments?

**Comment by artiction** [comment]
Alright, it works fortunately. Thanks for the fix!

**Comment by xenova** [comment]
> Alright, it works fortunately. Thanks for the fix!

Okay. This does mean it was a 429 error (Too many requests). If this happens again, please send me the output for me to write a better error message. Thanks!
