### ISSUE TITLE
Tracebacks

### ISSUE THREAD

**Issue by artiction** [xenova/chat-replay-downloader#49]
```
Traceback (most recent call last):
  File "C:\Users\\Downloads\Compressed\chat-replay-downloader-1.0.2\tester.py", line 641, in <module>
    chat_messages = chat_downloader.get_chat_replay(
  File "C:\Users\\Downloads\Compressed\chat-replay-downloader-1.0.2\tester.py", line 565, in get_chat_replay
    return self.get_youtube_messages(match.group(1), start_time, end_time, message_type, chat_type, callback)
  File "C:\Users\\Downloads\Compressed\chat-replay-downloader-1.0.2\tester.py", line 408, in get_youtube_messages
    info = self.__get_live_info(continuation)
  File "C:\Users\r\Downloads\Compressed\chat-replay-downloader-1.0.2\tester.py", line 303, in __get_live_info
    return(self.__get_continuation_info(url))
  File "C:\Usersr\Downloads\Compressed\chat-replay-downloader-1.0.2\tester.py", line 307, in __get_continuation_info
    info = self.__session_get_json(url)
  File "C:\Users\Downloads\Compressed\chat-replay-downloader-1.0.2\tester.py", line 145, in __session_get_json
    return self.__session_get(url).json()
  File "C:\Users\\AppData\Local\Programs\Python\Python39\lib\site-packages\requests\models.py", line 900, in json
    return complexjson.loads(self.text, **kwargs)
  File "C:\Users\\AppData\Local\Programs\Python\Python39\lib\json\__init__.py", line 346, in loads
    return _default_decoder.decode(s)
  File "C:\Users\AppData\Local\Programs\Python\Python39\lib\json\decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "C:\Users\\AppData\Local\Programs\Python\Python39\lib\json\decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

C:\Users\\Downloads\Compressed\chat-replay-downloader-1.0.2>python tester.py -message_type all https://www.youtube.com/watch?v=jJ8EkajpnAo -output jJ8EkajpnAo3.txt
Traceback (most recent call last):
  File "C:\Users\\Downloads\Compressed\chat-replay-downloader-1.0.2\tester.py", line 641, in <module>
    chat_messages = chat_downloader.get_chat_replay(
  File "C:\Users\\Downloads\Compressed\chat-replay-downloader-1.0.2\tester.py", line 565, in get_chat_replay
    return self.get_youtube_messages(match.group(1), start_time, end_time, message_type, chat_type, callback)
  File "C:\Users\\Downloads\Compressed\chat-replay-downloader-1.0.2\tester.py", line 408, in get_youtube_messages
    info = self.__get_live_info(continuation)
  File "C:\UsersDownloads\Compressed\chat-replay-downloader-1.0.2\tester.py", line 303, in __get_live_info
    return(self.__get_continuation_info(url))
  File "C:\Users\Downloads\Compressed\chat-replay-downloader-1.0.2\tester.py", line 307, in __get_continuation_info
    info = self.__session_get_json(url)
  File "C:\Users\\Downloads\Compressed\chat-replay-downloader-1.0.2\tester.py", line 145, in __session_get_json
    return self.__session_get(url).json()
  File "C:\Users\\AppData\Local\Programs\Python\Python39\lib\site-packages\requests\models.py", line 900, in json
    return complexjson.loads(self.text, **kwargs)
  File "C:\Users\\AppData\Local\Programs\Python\Python39\lib\json\__init__.py", line 346, in loads
    return _default_decoder.decode(s)
  File "C:\Users\\AppData\Local\Programs\Python\Python39\lib\json\decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "C:\Users\\AppData\Local\Programs\Python\Python39\lib\json\decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
```

**Comment by artiction** [comment]
Are you sure that the files aren't updating by itself? The amount of tracebacks I've been getting is insane. I have to regularly check if the script has crashed or not and when I do reset the script, I have to do it with 5 to countless times for it to work and not giving me a traceback.. The 1.02 version (which Im currently using) was working so well but now it's like this. Im very sure it isn't my internet..
\

**Comment by ccdffddfddfdsfedeee** [comment]
Try this version: https://pastebin.com/mZp2bJGE

**Comment by xenova** [comment]
Hi there, please see [this comment:](https://github.com/xenova/chat-replay-downloader/issues/48#issuecomment-769423878).

> Why does the script seem to be always connected / updated that its problem shifts from time to time?

As I have said before, the code does not automatically update on your end. You have to actually install it/update it manually (unless you have explicitly set a tool to synchronise with the repo)



> The fact that Im getting the exact same error after reinstalling just shows that the older releases are connected to the newer ones. Why does this happen? Im genuinely confused and so tired of this. Using older releases just don't work anymore.

Yes I am aware of this now as seen in #48 . I am looking to get a fix out as soon as possible.

**Comment by xenova** [comment]
## An update to those waiting:
I have **found the problem** and I will fix it as soon as possible.

In short, YouTube removed support for an endpoint which this tool (and many others) used to get chat. They removed https://www.youtube.com/live_chat_replay/get_live_chat_replay and are now using https://www.youtube.com/youtubei/v1/live_chat/get_live_chat_replay and https://www.youtube.com/youtubei/v1/live_chat/get_live_chat.

**Comment by artiction** [comment]
> Try this version: https://pastebin.com/mZp2bJGE
Looks like it can't parse video data or either it's a problem on my connection.

> ## An update to those waiting:
Alright, I'll settle with OBS for now. Thanks for responding.

**Comment by Gremuar** [comment]
> ## An update to those waiting:
> I have **found the problem** and I will fix it as soon as possible.
> 
> In short, YouTube removed support for an endpoint which this tool (and many others) used to get chat. They removed https://www.youtube.com/live_chat_replay/get_live_chat_replay and are now using https://www.youtube.com/youtubei/v1/live_chat/get_live_chat_replay and https://www.youtube.com/youtubei/v1/live_chat/get_live_chat.

Thanks. Replacement on line 300:
format ('live_chat_replay', 'get_live_chat_replay')
on
format ('live_chat', 'get_live_chat_replay')
Solved my problem.

**Comment by xenova** [comment]
Alright - I've been working a lot recently to get an updated/fixed version out for you all to use and test... and I think the `package` branch is ready for use. I still need to add a lot of documentation, but this will be much more useful than the current version in `master` (which doesn't work currently due to YouTube API endpoint changes).

This version is **much** more advanced than the original version. Some of the options are slightly different from version 1, but the help command (`chat_replay_downloader -h`) should assist you in the meantime while I write better documentation. 

### You can install it using `pip install chat-replay-downloader` (see https://pypi.org/project/chat-replay-downloader/ for more info).

Please let me know your thoughts and feel free to give suggestions! You can always post an issue or even create a pull request.

**Comment by Kaimeera** [comment]
ModuleNotFoundError: No module named 'docstring_parser'

**Comment by artiction** [comment]
```
  File "C:\Users\x\Downloads\chat-replay-downloader-master\chat_replay_downloader\tester.py", line 8, in <module>
    from .sites.common import SiteDefault
ImportError: attempted relative import with no known parent package
```
Similar error here.

**Comment by xenova** [comment]
> `ModuleNotFoundError: No module named 'docstring_parser' `
> FWIW-- if I run chat-replay-dwnloader -h I get
> `ImportError: attempted relative import with no known parent package `


> ```
>   File "C:\Users\x\Downloads\chat-replay-downloader-master\chat_replay_downloader\tester.py", line 8, in <module>
>     from .sites.common import SiteDefault
> ImportError: attempted relative import with no known parent package
> ```
> 
> Similar error here.



Did you run it in the correct way?

The project now uses python packaging. This means there are a number of ways to use it:
1. `pip install chat-replay-downloader` will download it from the python packaging index. You can then use it as `chat_replay_downloader` from **any** location on your computer.
2. If you downloaded the repository (i.e. if you want to see the source code), you can do `make install` inside the project's root folder. You can then use it as above.
3. If you have installed all the dependencies (i.e. using `pip install <x>`), you can even run it as `python -m chat_replay_downloader` inside the root folder)

**Comment by artiction** [comment]
Alright, it works. I should've followed that pip install instead of running it for requirements only. Thanks a lot for the fix!

**Comment by xenova** [comment]
> Alright, it works. I should've followed that pip install instead of running it for requirements only. Thanks a lot for the fix!

No problem! Glad to finally get this updated version out.

**Comment by Kaimeera** [comment]
Thanks! I've got it working now, I was missing a dependency. Really like this version!

**Comment by xenova** [comment]
> Thanks! I've got it working now, I was missing a dependency. Really like this version!

Awesome! Really glad to hear that! I am also writing better documentation as we speak.
