### ISSUE TITLE
zsh: command not found: chat_replay_downloader

### ISSUE THREAD

**Issue by amirpixel** [xenova/chat-replay-downloader#54]
* chat-replay-downloader version: v0.0.8
* Python version: Python 2.7
* Operating System: MacOS

### Description
Hey ya'll,
First off, thanks for creating such a handy tool, and sorry if this is a newbie question. I recently got a Mac, so I still haven't gotten used it.

I tried the tool on Windows and it works perfectly, without any issues.
However, on my Mac, I just can't get it to work.
I've installed the package using pip install.
I've also cloned the git repository.

But when I use the 'chat_replay_downloader' command in terminal and VS code, I get a `zsh: command not found: chat_replay_downloader` error.

I'm sure there's an easy way to fix this, but wanted to check with ya.

On Windows, I simply used the pip command, installed the tool and ran the chat_replay_downloader command and it worked without any issues.

Any Ideas how to fix this?

Cheers,

### What I Did

```
amir@Amirs-MBP chat-replay-downloader % chat_replay_downloader 
zsh: command not found: chat_replay_downloader
amir@Amirs-MBP chat-replay-downloader % chat_replay_downloader -h
zsh: command not found: chat_replay_downloader
amir@Amirs-MBP ~ % python chat_replay_downloader.py https://www.youtube.com/watch?v=xxxxx -start_time 14400 -end_time 15000 -output example.csv
zsh: no matches found: https://www.youtube.com/watch?v=xxxxx
amir@Amirs-MBP ~ % python chat_replay_downloader.py https://www.youtube.com/watch?v=xxxxx -output chat.csv   
zsh: no matches found: https://www.youtube.com/watch?v=xxxxx```

**Comment by xenova** [comment]
> * Python version: Python 2.7

Hi there, this is your issue. The tool is only supported by Python 3. Python 2 has reached its "End of Life" ([source](https://www.python.org/doc/sunset-python-2/)) and so we will not be supporting it. For some reason, mac still uses Python2 by default.

To fix your problem, run the same commands but replace `python` with `python3` and `pip` with `pip3`. Hope this helps!

**Comment by amirpixel** [comment]
> To fix your problem, run the same commands but replace `python` with `python3` and `pip` with `pip3`. Let me know if you have any other questions.

Thank you so much! So weird that Mac uses Python 2, I didn't even notice that until you mentioned it. I've updated Python, reinstalled the package and ran it again. It worked perfectly. 
Thanks again for creating this amazing tool. Super handy
