### ISSUE TITLE
Failed, Didn't work (SyntaxError: invalid syntax)

### ISSUE THREAD

**Issue by danlovam** [xenova/chat-replay-downloader#8]
I followed the instructions (installed all the requirements except (csv) (didn't install), and when I tried to execute the command to download (all the chat), I got an error message, here is my example:

- the command:
`Debian@Linux$ python chat_replay_downloader.py https://www.youtube.com/watch?v=xEEdiQ_B62I -output NewFile.txt
`

- and I got this error message in the terminal:

```
  File "chat_replay_downloader.py", line 252
    print('['+message['time_text']+']',message['author']+':',message['message'],file=f)
                                                                                    ^
SyntaxError: invalid syntax
```

I'm not sure if it is a bug or do I miss something?
thanks

**Comment by xenova** [comment]
Let me check that out. I am running it now, and it seems to be working? 
[NewFile.txt](https://github.com/xenova/chat-replay-downloader/files/5011125/NewFile.txt)

**Comment by xenova** [comment]
What version of python are you using? This might be because you are using 2.x, while the tool requires 3.x

**Comment by danlovam** [comment]
yes, I use the version:
Python 2.7.16

**Comment by xenova** [comment]
Okay, that is the problem. You need to upgrade to the Python 3.
Python 2 has reached End Of Life (1st January 2020) https://www.python.org/doc/sunset-python-2/ and your version (Python 2.7.x) is deprecated.

That will fix it.

**Comment by danlovam** [comment]
I'm working on it
thank you very much

**Comment by xenova** [comment]
No problem, let me know if it works so I can close the issue :)
